name: project-ilaila

services:
  app:
    build: 
      context: ..
      dockerfile: .devcontainer/app.Dockerfile
    tty: true
    command: sleep infinity
    volumes:
      - ..:/home/dev/app:cached
      
      - pnpm_store:/home/dev/app/.pnpm-store
      - pnpm_packages:/home/dev/app/node_modules/.pnpm
      - pnpm_bin:/home/dev/app/node_modules/.bin
      
      - /home/dev/app/node_modules
      - /home/dev/app/.next

    depends_on:
      - db

  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "00000000"
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
  pnpm_store:
  pnpm_packages:
  pnpm_bin: